### PR TITLE
Fix incorrect reported file in error message when missing a required semicolon.

### PR DESCRIPTION
**Pull request by Fyren**
This would only happen with `#pragma semicolon 1` if a semicolon was missing after some other file was included.

Without the change, the error reported for the test case would be in the empty include (though with the correct line number).

### CODE REVIEW

**Comment by peace-maker** [comment]
Are you sure the test is correct? You're including a nonexistent file. Maybe I'm not understanding the bug here.

**Comment by Fyren** [comment]
I'm including an almost empty file.  Try the test against master (i.e. without this PR) and the error reported will be in the empty file.

Almost empty because apparently if you try to include an actual 0-byte file, spcomp will error.

**Comment by asherkin** [comment]
> I'm including an almost empty file. Try the test against master (i.e. without this PR) and the error reported will be in the empty file.

I think it got renamed at one point, the filename here does indeed seem wrong.

**Comment by Fyren** [comment]
I did rename it, but the test still passed because the check was lax.  Fixed, thanks.

**Pull request merged**
