### PR TITLE
Fix register increment/decrement visit

### PR DESCRIPTION
**Pull request by Kailo97**
Probably copy-paste mistake.

### CODE REVIEW

**Comment by dvander** [comment]
Looks good, nice catch - was there a test case that caused this, that we could add to the suite?

**Comment by Kailo97** [comment]
Just found this while looking for code (writing bytecode reference). sc4.cpp saying that "inc/dec.alt" not generatable by original SP compiler. But it can be generated by "emit" supported compiler or as direct smx modification.

**Comment by dvander** [comment]
Hrm, okay. With ungenerated opcodes I'd prefer to remove them from the verifier & VM. It makes the implementation surface a bit smaller. Lemme first make sure it didn't appear in older versions or anything though.

**Comment by dvander** [comment]
Well, it's never been used, but might as well keep it around. It's already implemented.

**Pull request merged**
