### PR TITLE
Fixed AMBuildScript for build option

### PR DESCRIPTION
**Pull request by WildCard65**

### CODE REVIEW

**Comment by dvander** [comment]
Shouldn't this be `getattr(builder.options, 'build')`?

**Comment by WildCard65** [comment]
@dvander IDK, I barely know anything about AMBuild, I just followed with how Configure() gets amtl from options, this change does work as intended though.

**Comment by dvander** [comment]
This clearly does not read from `builder.options.build` anymore, so it doesn't work except that it probably falls through to the last case by accident.

**Comment by WildCard65** [comment]
From my testing, this change does cycle to proper build option instead of
what current behaviour does which is build everything

**Pull request merged**
